### PR TITLE
ResolveWithService being called twice due to Expression.Condition 

### PR DESCRIPTION
**Pull request by bzbetty**
the fix for #221 added a expression.condition, this accidentally evaluates ResolveWithService calls twice which can make multiple db requests.

Using Expression.Coalesce is a better choice but does mean we need to return an empty list instead of null (don't think that's a bad thing but it is a change).

### CODE REVIEW

**Comment by lukemurray** [comment]
Why can't we return `null`? It'd be good to respect the schema and if `null` is a valid response it should be used.

Might need to use the wrapInNullCheck logic here too.

**Comment by bzbetty** [comment]
i wouldn't have an issue with a null return, i believe it was Bosch-Eli-Black that had the original issue.

**Comment by lukemurray** [comment]
I mean why does using `Expression.Coalesce` force us to return a `null`?

I guess I'll dig into it :)

**Comment by bzbetty** [comment]
ah right, can't return null because of the ToList call that happens afterwards.

**Pull request merged**
