### PR TITLE
make error variable values more distinctive

### PR DESCRIPTION
**Pull request by taipignas**
I noticed that some error messages returned are harder to quickly grasp. i think this should make them more readable. should i do it for all exceptions all variables or is this enough for now?

### CODE REVIEW

**Comment by lukemurray** [comment]
This is good thanks, just need to fix some of the tests that test for the errors.

**Comment by taipignas** [comment]
i am having trouble running the project. i have java command and antlr4 command available but the project will still not build. i think its because i installed Amazon Corretto and jre is integrated inside jdk.

**Comment by bzbetty** [comment]
@taipignas building on windows, Mac or Linux? I suspect @lukemurray might be a Mac as I have similar issue to you. I normally have to remove a line from the project file.

**Comment by lukemurray** [comment]
I am on a Mac. If you have java installed you should be able to `<JavaExec>/usr/bin/java</JavaExec>` in `EntityGraphQL.csproj` to the path.

**Comment by taipignas** [comment]
im on windows, i had to use "<JavaExec>C:\Program Files\Amazon Corretto\jdk21.0.2_13\bin\java.exe</JavaExec>" and now it works

thank you for adapting the tests and merging it!

**Pull request merged**
