### PR TITLE
bugfix: ParameterReplacerBenchmark & Performance Fix

### PR DESCRIPTION
**Pull request by bzbetty**
another for #275

### CODE REVIEW

**Comment by lukemurray** [comment]
Oh I see you have a more realistic test in `SetupLargerSetOfWhereWhens`. 👍

**Comment by bzbetty** [comment]
> play with more to see if it impacts cached queries

I didn't think there was any expression tree caching? It was something I was thinking of suggesting

**Comment by bzbetty** [comment]
Also have a feeling the parameter replacer runs twice in a row on the same expression so I think there's more room for improvement.

**Comment by lukemurray** [comment]
Yeh, not expression tree caching. But the nodes get cached for matching queries. just need to double check the lifetime of the replacer.

Any ideas where it might be running twice in a row? I'm looking into this general issue now.

**Comment by bzbetty** [comment]
>Any ideas where it might be running twice in a row? I'm looking into this general issue now.

On review I think i was mistaken.

Field.PrepareFieldExpression called replace, which then returns to GetExpression which called it too, but looks like the arguments are different.  Could potentially have savings by traversing once instead of twice, but wasn't as wasteful as I first thought.

**Pull request merged**
