### PR TITLE
Add markdown documentation for caching

### PR DESCRIPTION
**Pull request by PhilippeWaeber**
- Describe wiring in Program.cs
- Describe custom IOutputCachePolicy
- Add it as the last page, until we decide where to put it

Relates to #345

### CODE REVIEW

**Comment by PhilippeWaeber** [comment]
@lukemurray I've added the page last but would suggest adding it after validation (index 7) and move the ones below one index further down.
Any other feedback welcome. Feel free to adapt the doc.

**Comment by PhilippeWaeber** [comment]
@bzbetty Could be worth setting up a `Chaching` page with different chapters. Let's wait for input.

**Comment by PhilippeWaeber** [comment]
@bzbetty I've slightly adapted the page to hold documentation for different caching techniques. Please add your part in there.
@lukemurray Where to put it? After Validation (index 7) ? Anything else to do besides setting `sidebar_position: 13` in the file itself?

**Comment by lukemurray** [comment]
That should be it. You can run `npm start` from the `docs` directory to test it.

**Comment by PhilippeWaeber** [comment]
Cheers, looks good to me 👍 
Thanks for your help an this lib.

**Comment by bzbetty** [comment]
Not worth writing a lot about EFCoreSecondLevelCacheInterceptor as it's fairly well documented itself and doesn't require EQL to be changed.  But here's some brief docs, i could put them in another PR once this is merged.



## EFCore Second Leve Cache Interceptor

EFCoreSecondLevelCacheInterceptor is a library that caches the result of EF commands and automatically invalidates cached data by watching what tables are updated via EF.  This makes it a really easy way to speed up the performance of EntityGraphQL without the overhead of manual invalidation.  EQL still needs to parse queries and convert them to expression trees, so there's still more cpu than output caching.

It supports numerous caching methods through its support of EasyCaching.Core (InMemory, Redis, Sql, Disk + more).

For full setup instructions see their documentation on their github page (https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor) however it can be as simple as enabling efsecondlevelcache, adding a caching provider and adding the intercepter to EFCore.

```
  services.AddEFSecondLevelCache(options => {
     options.UseMemoryCacheProvider();
  });

  services.AddDbContextPool<ApplicationDbContext>((serviceProvider, optionsBuilder) => {
     optionsBuilder
        .UseSqlServer(...)
        .AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>()));
  });

```

**Pull request merged**
